def ValueException(value):
    print(f"{value}의 값이 올바르지 않습니다!")